const DISPOSABLE_DOMAINS = new Set(
  [
    'mailinator.com',
    'tempmail.com',
    'temp-mail.org',
    'guerrillamail.com',
    'guerrillamail.info',
    'guerrillamail.de',
    'sharklasers.com',
    'grr.la',
    'spam4.me',
    'yopmail.com',
    'yopmail.fr',
    'yopmail.net',
    'trashmail.com',
    'trashmail.net',
    'trashmail.org',
    'throwawaymail.com',
    'getairmail.com',
    'mailnesia.com',
    'maildrop.cc',
    'mailcatch.com',
    'fakeinbox.com',
    'fakemail.net',
    'dispostable.com',
    '10minutemail.com',
    '10minutemail.net',
    'minutemail.com',
    'mail.tm',
    'mailinator.net',
    'mailinator.org',
    'mailinator2.com',
    'spamgourmet.com',
    'jetable.org',
    'jetable.com',
    'nospam.ze.tc',
    'mytemp.email',
    'tempmail.dev',
    'tempmail.plus',
    'tempr.email',
    'discardmail.com',
    'discardmail.de',
    'mailexpire.com',
    'mailforspam.com',
    'spam.law.com',
    'binkmail.com',
    'safetymail.info',
    'sogetthis.com',
    'spamhereplease.com',
    'superrito.com',
    'thisisnotmyrealemail.com',
    'throwawayemailaddress.com',
    'tmailinator.com',
    'mailf8.com',
    'tmail.ws',
    'mt2015.com',
    'emailias.com',
    'jourrapide.com',
    'mailtemp.info',
    'temp-mail.io',
    'mail-temp.com',
    'dispost.com',
    'front8.com',
    'rhyta.com',
    'kurzepost.de',
    'zaubamail.com',
    'spambox.us',
    'mailcan.com',
    'cheapmalize.com',
    'mailfuel.com',
    'btejrf.com',
    'wgayg.com',
    'hqtra.com',
    'techemail.com',
    'mailinator8.com',
    'vegnirewire.com'
  ].map((d) => d.toLowerCase())
);

export function isDisposableEmail(email: string): boolean {
  const domain = email.split('@')[1]?.toLowerCase().trim() ?? '';
  if (!domain) return false;
  if (DISPOSABLE_DOMAINS.has(domain)) return true;
  return false;
}